name: Build, Scan, and Push Docker Image to ECR

on:
  push:
    branches:
      - master

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: user-service-docker

permissions:
  contents: write
  id-token: write

jobs:
  build-scan-push:
    runs-on: ubuntu-latest

    steps:

      # Generate GitHub App token
      - name: Generate GitHub App Token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      # Checkout repository using GitHub App token
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}

      - name: Test automation
        run: echo "GitHub App authentication successful-1"

      # Gitleaks scan
      - name: Scan repository for secrets (gitleaks)
        continue-on-error: true
        run: |
          curl -sSL https://github.com/gitleaks/gitleaks/releases/download/v8.18.1/gitleaks_8.18.1_linux_x64.tar.gz | tar -xz
          sudo mv gitleaks /usr/local/bin/gitleaks
          gitleaks detect --redact --verbose

      # Configure AWS credentials using OIDC
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::905418043476:role/GitHubECRAccessRole
          aws-region: ${{ env.AWS_REGION }}

      # Setup Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Login to ECR
      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # Detect environment from branch
      - name: Determine environment and Helm values path
        id: env
        run: |
          BRANCH="${GITHUB_REF_NAME}"
          if [[ "$BRANCH" == "dev_environment" ]]; then
            ENV="dev"
            VALUES_FILE="helm_growstack/values.yaml"
          elif [[ "$BRANCH" == "staging_environment" ]]; then
            ENV="staging"
            VALUES_FILE="staging_helm_growstack/values.yaml"
          elif [[ "$BRANCH" == "master" ]]; then
            ENV="prod"
            VALUES_FILE="prod_helm_growstack/values.yaml"
          else
            echo "Unsupported branch"
            exit 1
          fi

          echo "env_name=$ENV" >> "$GITHUB_OUTPUT"
          echo "values_file=$VALUES_FILE" >> "$GITHUB_OUTPUT"

      # Create image tag
      - name: Set image tag
        id: vars
        run: |
          IMAGE_TAG="$(echo $GITHUB_SHA | cut -c1-7)-${{ steps.env.outputs.env_name }}"
          echo "IMAGE_TAG=$IMAGE_TAG" >> "$GITHUB_OUTPUT"

      # Build Docker Image
      - name: Build Docker image
        run: |
          docker build \
            --build-arg AWS_ACCESS_KEY=${{ secrets.AWS_ACCESS_KEY }} \
            --build-arg AWS_SECRET_KEY=${{ secrets.AWS_SECRET_KEY }} \
            --build-arg AWS_BUCKET_NAME=${{ secrets.AWS_BUCKET_NAME }} \
            --build-arg AWS_REGION=${{ secrets.AWS_REGION }} \
            --build-arg APPLICATION_ENV=${{ steps.env.outputs.env_name }} \
            --build-arg DEV_MODE=${{ secrets.DEV_MODE }} \
            --build-arg PORT=${{ secrets.PORT }} \
            -t $ECR_REPOSITORY:${{ steps.vars.outputs.IMAGE_TAG }} .

      # Push Docker image
      - name: Push image to ECR
        run: |
          docker tag $ECR_REPOSITORY:${{ steps.vars.outputs.IMAGE_TAG }} \
          ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ steps.vars.outputs.IMAGE_TAG }}

          docker push \
          ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ steps.vars.outputs.IMAGE_TAG }}

      - name: Output final image URI
        run: |
          echo "Pushed image:"
          echo "${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ steps.vars.outputs.IMAGE_TAG }}"

      # Checkout Infra Repo
      - name: Checkout Helm repo
        uses: actions/checkout@v4
        with:
          repository: GrowStack-ai/GrowStackAI-Infra
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          path: infra_repo
          ref: main

      # Update Helm values.yaml
      - name: Update Helm values.yaml
        working-directory: infra_repo
        run: |
          service="backend"
          new_tag=${{ steps.vars.outputs.IMAGE_TAG }}
          values_file="${{ steps.env.outputs.values_file }}"

          sed -i "/^[[:space:]]$service:/,/^[[:space:]]*port:/ s|^\([[:space:]]*tag:[[:space:]]\).*|\1${new_tag}|" "$values_file"

          cat "$values_file"

      # Commit and push
      - name: Commit and push updated values.yaml
        working-directory: infra_repo
        run: |
          values_file="${{ steps.env.outputs.values_file }}"
          new_tag=${{ steps.vars.outputs.IMAGE_TAG }}

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add "$values_file"
          git diff --cached --quiet || git commit -m "Update backend image tag to ${new_tag}"
          git push origin main
